config-version: 2
name: 'recurly'

version: '0.3.1'
require-dbt-version: [">=1.3.0", "<2.0.0"]

models:
  recurly:
    +schema: recurly
    +materialized: table
    intermediate:
      +schema: recurly_int
      +materialized: table

vars:
  recurly:
    account_balance_history: "{{ ref('stg_recurly__account_balance_history') }}"
    account_history: "{{ ref('stg_recurly__account_history') }}"
    account_note_history: "{{ ref('stg_recurly__account_note_history') }}"
    billing_info_history: "{{ ref('stg_recurly__billing_info_history') }}"
    coupon_discount: "{{ ref('stg_recurly__coupon_discount') }}"
    coupon_redemption_history: "{{ ref('stg_recurly__coupon_redemption_history') }}"
    credit_payment_history: "{{ ref('stg_recurly__credit_payment_history') }}"
    invoice_coupon_redemption_history: "{{ ref('stg_recurly__invoice_coupon_redemption_history') }}"
    invoice_history: "{{ ref('stg_recurly__invoice_history') }}"
    invoice_subscription_history: "{{ ref('stg_recurly__invoice_subscription_history') }}"
    line_item_history: "{{ ref('stg_recurly__line_item_history') }}"
    plan_currency_history: "{{ ref('stg_recurly__plan_currency_history') }}"
    plan_history: "{{ ref('stg_recurly__plan_history') }}"
    subscription_add_on_history: "{{ ref('stg_recurly__subscription_add_on_history') }}"
    subscription_change_history: "{{ ref('stg_recurly__subscription_change_history') }}"
    subscription_history: "{{ ref('stg_recurly__subscription_history') }}"
    transaction_subscription: "{{ ref('stg_recurly__transaction_subscription') }}"
    transaction: "{{ ref('stg_recurly__transaction') }}"
  recurly_account_pass_through_columns: []
  recurly_subscription_pass_through_columns: []
